#!/usr/bin/env php
<?php

require __DIR__ . '/core/Application.php';
require __DIR__ . '/commands/GreetCommand.php';
require __DIR__ . '/commands/MakeModelCommand.php';
require __DIR__ . '/commands/MakeControllerCommand.php';
require __DIR__ . '/commands/MakeViewCommand.php';

use Core\Application;
use Commands\GreetCommand;
use Commands\MakeModelCommand;
use Commands\MakeControllerCommand;
use Commands\MakeViewCommand;

$app = new Application();
$app->addCommand(new GreetCommand());
$app->addCommand(new MakeModelCommand());
$app->addCommand(new MakeControllerCommand());
$app->addCommand(new MakeViewCommand());
$app->run();
